nginx:
    build: ./nginx/
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - app

php:
    build: ./php/
    expose:
        - 9000
    links:
        - mysql
    volumes_from:
        - app

app:
    image: clemenshemmerling/rpi-php:7.0.5-fpm-alpine
    volumes:
        - ./app/:/var/www/html
    command: "true"

mysql:
    image: hypriot/rpi-mysql
    volumes_from:
        - data
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: project
        MYSQL_USER: project
        MYSQL_PASSWORD: project

data:
    image: hypriot/rpi-mysql
    volumes:
        - /var/lib/mysql
    command: "true"
